name: Release with goreleaser
on:
  push:
    tags:
      - v*.*
jobs:
        
  release-linux-amd64:
    name: Release Go Binary for linux amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.16
        project_path: "./src"
        build_flags: "-buildmode=pie"
        ldflags: "-s -w"
        
  release-linux-386:
    name: Release Go Binary for linux 386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: 386
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
        
  releases-matrix-darwin:
    name: Release Go Binary for Darwin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
        project_path: "./src"
        ldflags: "-s -w"
